/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package il.ac.hit.costmanager.view.category;

import il.ac.hit.costmanager.model.category.Category;
import il.ac.hit.costmanager.view.builders.ButtonBuilder;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;

/**
 * @author Birbal
 */
public class CategoryView extends javax.swing.JFrame implements ICategoryView {

    private ICategoryViewModel viewModel;
    private CategoryUI categoryUI;

    public CategoryView() {
        this.categoryUI = new CategoryUI();
    }

    @Override
    public void setViewModel(ICategoryViewModel vm) {
        this.viewModel = vm;
    }

    @Override
    public void showCategories(ArrayList<Category> catModel) {
        this.categoryUI.showCategories(catModel);
    }

    public class CategoryUI {
        private javax.swing.JButton btnDelete;
        private javax.swing.JButton btnSubmit;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JTable tabShowCategories;
        private javax.swing.JTextField txtAddNewCat;


        public CategoryUI() {
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        private void initComponents() {

            jPanel1 = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            txtAddNewCat = new javax.swing.JTextField();

            btnSubmit = new ButtonBuilder("Submit").build();
            btnSubmit.addActionListener(this::btnSubmitActionPerformed);

            jSeparator1 = new javax.swing.JSeparator();
            jScrollPane1 = new javax.swing.JScrollPane();
            tabShowCategories = new javax.swing.JTable();
            btnDelete = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jPanel1.setBackground(new java.awt.Color(102, 102, 255));

            jLabel1.setFont(new java.awt.Font("Times New Roman", Font.BOLD, 24)); // NOI18N
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("Add Categories");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
            );
            jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(jLabel1)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jLabel2.setFont(new java.awt.Font("Times New Roman", Font.BOLD, 12)); // NOI18N
            jLabel2.setText("Add New Categorie :");


            tabShowCategories.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{
                            {null, null},
                            {null, null},
                            {null, null},
                            {null, null}
                    },
                    new String[]{
                            "Category Id", "Category Name"
                    }
            ) {
                boolean[] canEdit = new boolean[]{
                        false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            });
            jScrollPane1.setViewportView(tabShowCategories);

            btnDelete.setBackground(new java.awt.Color(102, 102, 255));
            btnDelete.setFont(new java.awt.Font("Times New Roman", Font.BOLD, 12)); // NOI18N
            btnDelete.setText("Delete");
            btnDelete.setContentAreaFilled(false);
            btnDelete.setDefaultCapable(false);
            btnDelete.setOpaque(true);
            btnDelete.addActionListener(this::btnDeleteActionPerformed);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtAddNewCat, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnSubmit)
                                    .addContainerGap(54, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDelete)
                                    .addGap(55, 55, 55))
                            .addComponent(jScrollPane1)
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(txtAddNewCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnSubmit))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDelete)
                                    .addContainerGap())
            );

            pack();
        }

        private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {
            if (txtAddNewCat.getText().trim().length() > 0) {
                viewModel.insertCategory(txtAddNewCat.getText().trim());
                txtAddNewCat.setText("");
                JOptionPane.showMessageDialog(null, "Category Inserted Successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Please inert category name");
            }
        }

        // this button click delete category in database
        private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
            int column = 0;
            int row = tabShowCategories.getSelectedRow();
            int value = Integer.parseInt(tabShowCategories.getModel().getValueAt(row, column).toString());
            viewModel.deleteCategory(value);
        }

        public void showCategories(ArrayList<Category> catModel) {
            Object[] data = new Object[2];
            DefaultTableModel tabModel = (DefaultTableModel) tabShowCategories.getModel();
            tabModel.getDataVector().removeAllElements();
            for (Category category : catModel) {
                data[0] = category.getCatId();
                data[1] = category.getCategoryName();
                tabModel.addRow(data);
            }
            tabShowCategories.setModel(tabModel);
        }
    }
}
